### ISSUE TITLE
Failure to printStackTrace

### ISSUE THREAD

**Issue by jasonjckn** [pallet/pallet-lein#3]
BASH#> lein pallet lift backtype.storm.nodes/nimbus :make

Feb 7, 2011 8:38:08 PM clojure.contrib.logging$impl_write_BANG_ invoke
INFO: extensions (:ssh)
Feb 7, 2011 8:38:14 PM clojure.contrib.logging$impl_write_BANG_ invoke
INFO: extensions (:ssh)
Feb 7, 2011 8:38:15 PM clojure.contrib.logging$impl_write_BANG_ invoke
INFO: retrieving nodes
Wrong number of args (1) passed to: core$map
Exception in thread "main" java.lang.IllegalArgumentException: No matching field found: .printStackTrace for class java.lang.IllegalArgumentException (NO_SOURCE_FILE:1)
    at clojure.lang.Compiler.eval(Compiler.java:5440)
    at clojure.lang.Compiler.eval(Compiler.java:5415)
    at clojure.lang.Compiler.eval(Compiler.java:5415)
    at clojure.lang.Compiler.eval(Compiler.java:5391)
    at clojure.core$eval.invoke(core.clj:2382)
    at clojure.main$eval_opt.invoke(main.clj:235)
    at clojure.main$initialize.invoke(main.clj:254)
    at clojure.main$null_opt.invoke(main.clj:279)
    at clojure.main$main.doInvoke(main.clj:354)
    at clojure.lang.RestFn.invoke(RestFn.java:422)
    at clojure.lang.Var.invoke(Var.java:369)
    at clojure.lang.AFn.applyToHelper(AFn.java:165)
    at clojure.lang.Var.applyTo(Var.java:482)
    at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: No matching field found: .printStackTrace for class java.lang.IllegalArgumentException
    at clojure.lang.Reflector.getInstanceField(Reflector.java:245)
    at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:267)
    at pallet.main$report_unexpected_exception.invoke(main.clj:90)
    at pallet.main$pallet_task.invoke(main.clj:141)
    at pallet.main$_main.doInvoke(main.clj:147)
    at clojure.lang.RestFn.invoke(RestFn.java:483)
    at clojure.lang.Var.invoke(Var.java:381)
    at user$eval231.invoke(NO_SOURCE_FILE:1)
    at clojure.lang.Compiler.eval(Compiler.java:5424)
    ... 13 more

**Comment by hugoduncan** [comment]
Fixed by https://github.com/pallet/pallet/commit/e5c18cf818fa7251879aadd2dd50143fcac2ade0
